[package]
name = "rtmp-ingress"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
bytes = "1"
chrono = "0.4.38"
rml_rtmp = { git = "ssh://git@github.com/wavey-ai/rust-media-libs.git" }
tracing = "0.1.40"
futures = "0.3.30"
xmpegts = { git = "ssh://git@github.com/wavey-ai/xiu" }
mse_fmp4 = { git = "ssh://git@github.com/wavey-ai/mse_fmp4.git" }
srt-tokio = "0.4.4"
tokio-stream = "0.1.15"
access-unit = "0.1.1"
